version: '3'

services:
  redoc:
    image: 'redocly/redoc:latest'
    volumes:
      - '.:/usr/share/nginx/html/openapi:cached'
    ports:
      - '8080:80'
    environment:
      SPEC_URL: 'http://localhost:8080/openapi/index.yaml'
      PAGE_TITLE: 'Doc API'
